"""2th

Revision ID: 3798a178d524
Revises: 80a0036bbf1e
Create Date: 2016-09-27 09:53:17.556283

"""

# revision identifiers, used by Alembic.
revision = '3798a178d524'
down_revision = '80a0036bbf1e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('body', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'body')
    ### end Alembic commands ###
